# Generated by Django 4.2.7 on 2025-11-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_text',
            field=models.BinaryField(blank=True, help_text='Encrypted message content (Fernet)', null=True),
        ),
    ]
