# Generated by Django 5.2.4 on 2025-12-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_meeting_meetinginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
